# Dynamic default values for InnoDB parameters.
# These can be overridden in group_vars or host_vars.

# pxc_innodb_buffer_pool_size:
#   The Buffer Pool is the primary area where InnoDB caches data and indexes.
#   For dedicated database servers, it's often set to 50-80% of physical memory.
#   This calculates 50% of ansible_memtotal_mb, converts it to GB, and ensures a minimum of 1G.
pxc_innodb_buffer_pool_size: "{{ [(((ansible_memtotal_mb | int) * 0.5) | int // 1024), 1] | max }}G"

# pxc_innodb_log_file_size:
#   The redo log file size is recommended to be about 25% of the Buffer Pool size.
#   Larger log files reduce checkpoint flushing frequency, improving throughput, but can
#   increase recovery time after a crash. This defaults to 12.5% (50% * 1/4) of memory,
#   with a minimum of 256MB.
pxc_innodb_log_file_size: "{{ [(((ansible_memtotal_mb | int) * 0.125) | int), 256] | max }}M"

# pxc_innodb_log_buffer_size:
#   The log buffer stores redo log data temporarily. MySQL 8.0 increased the default
#   to 16MB to avoid frequent disk writes for large transactions. This is a sensible default.
pxc_innodb_log_buffer_size: "16M"

# pxc_innodb_write_io_threads:
#   InnoDB uses background threads for I/O. It's recommended to set this to the number
#   of CPU cores to fully utilize disk and CPU resources. Defaults to 4 if core count is unknown.
pxc_innodb_write_io_threads: "{{ ansible_processor_vcpus | default(4) }}"

# pxc_innodb_read_io_threads:
#   Similar to write I/O threads, this is typically set to the number of CPU cores.
#   Defaults to the same value as write I/O threads.
pxc_innodb_read_io_threads: "{{ ansible_processor_vcpus | default(4) }}"

# pxc_innodb_purge_threads:
#   Purge threads are responsible for cleaning up old data versions. A common recommendation
#   is a quarter of the CPU cores, with a minimum of 1.
pxc_innodb_purge_threads: "{{ [(((ansible_processor_vcpus | default(1)) | int) // 4), 1] | max }}"

# pxc_innodb_max_dirty_pages_pct:
#   Controls the maximum percentage of dirty pages in the Buffer Pool. The default of 90%
#   allows for a higher volume of dirty pages, reducing background flushing I/O.
pxc_innodb_max_dirty_pages_pct: "90"

# pxc_innodb_flush_log_at_trx_commit:
#   Defines the redo log flushing strategy.
#   0: Write and flush to disk once per second.
#   1: Write and flush at every commit (highest durability).
#   2: Write at every commit, but flush only once per second (balances performance and durability).
#   A value of 2 is generally sufficient for PXC environments.
pxc_innodb_flush_log_at_trx_commit: "2"

# pxc_wsrep_slave_threads:
#   Number of threads for Galera replication. It's recommended to set this to
#   the number of CPU cores or half of the cores.
pxc_wsrep_slave_threads: "{{ ansible_processor_vcpus | default(2) }}"